#!/bin/bash

COMPILE_FLAG="-g"

g++  jh_stack.cc ${COMPILE_FLAG} -o jh_stack
if [ $? -eq 0 ]; then
	./jh_stack.exe
else
	echo
	echo "Compile Failed..."
	echo "Check out your code"
fi

gcc  jh_queue.c ${COMPILE_FLAG} -o jh_queue
if [ $? -eq 0 ]; then
	./jh_queue
else
	echo
	echo "Compile Failed..."
	echo "Check out your code"
fi

gcc jh_singly_linked_list.c ${COMPILE_FLAG} -o jh_singly_linked_list
if [ $? -eq 0 ]; then
	./jh_singly_linked_list
else
	echo
	echo "Compile Failed..."
	echo "Check out your code"
fi

gcc jh_search.c ${COMPILE_FLAG} -o jh_search
if [ $? -eq 0 ]; then
	./jh_search
else
	echo
	echo "Compile Failed..."
	echo "Check out your code"
fi

gcc jh_doubly_linked_list.c ${COMPILE_FLAG} -o jh_doubly_linked_list
if [ $? -eq 0 ]; then
	./jh_doubly_linked_list
else
	echo
	echo "Compile Failed..."
	echo "Check out your code"
fi

gcc jh_deque.c ${COMPILE_FLAG} -o jh_deque
if [ $? -eq 0 ]; then
	./jh_deque
else
	echo
	echo "Compile Failed..."
	echo "Check out your code"
fi

